### PR TITLE
Sof 13/feature/display buildings

### PR DESCRIPTION
**Pull request by lewisclark**
this PR pulls building information from the database to visualize as markers on the map

image

### CODE REVIEW

**Comment by JohanKool3** [comment]
I've ran the program with this branch and the buildings aren't being shown on my map. I'll try upgrading my versions. Here is the output I get in my emulator.

image

**Comment by lewisclark** [comment]
> I've ran the program with this branch and the buildings aren't being shown on my map. I'll try upgrading my versions. Here is the output I get in my emulator.
> 
> image

Oh yeah, I forgot to mention that populate.sql needs to be re-run on the database. The way I've been doing this during development is by adding a `|| true` to the condition [here](https://github.com/softengsquad/studentmap/blob/95a6f4d0a45a413791ea164581305b61a643eda4/lib/data_layer/database.dart#L18C1-L18C23). This will delete the database and force schema.sql and populate.sql to be executed again. 

I'm not too sure why the roads are showing black in your environment.

**Comment by JohanKool3** [comment]
> > I've ran the program with this branch and the buildings aren't being shown on my map. I'll try upgrading my versions. Here is the output I get in my emulator.
> > image
> 
> Oh yeah, I forgot to mention that populate.sql needs to be re-run on the database. The way I've been doing this during development is by adding a `|| true` to the condition [here](https://github.com/softengsquad/studentmap/blob/95a6f4d0a45a413791ea164581305b61a643eda4/lib/data_layer/database.dart#L18C1-L18C23). This will delete the database and force schema.sql and populate.sql to be executed again.
> 
> I'm not too sure why the roads are showing black in your environment.

There is a constant that we can use during debugging called **kDebugMode**, it is true when the program is run in debug mode - which means for those kind of features we can use it instead of adding and then removing code. https://api.flutter.dev/flutter/foundation/kDebugMode-constant.html

**Comment by lewisclark** [comment]
> > > I've ran the program with this branch and the buildings aren't being shown on my map. I'll try upgrading my versions. Here is the output I get in my emulator.
> > > image
> > 
> > 
> > Oh yeah, I forgot to mention that populate.sql needs to be re-run on the database. The way I've been doing this during development is by adding a `|| true` to the condition [here](https://github.com/softengsquad/studentmap/blob/95a6f4d0a45a413791ea164581305b61a643eda4/lib/data_layer/database.dart#L18C1-L18C23). This will delete the database and force schema.sql and populate.sql to be executed again.
> > I'm not too sure why the roads are showing black in your environment.
> 
> There is a constant that we can use during debugging called **kDebugMode**, it is true when the program is run in debug mode - which means for those kind of features we can use it instead of adding and then removing code. https://api.flutter.dev/flutter/foundation/kDebugMode-constant.html

Sweet. Just added this change.

**Review by JohanKool3 — APPROVED** [review]
Changes look good. Ready to merge :+1:

**Pull request merged**
